SET(CTEST_PROJECT_NAME "mke")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
SET(CTEST_NIGHTLY_IDENT_LOCATION "http://127.0.0.1/n")

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "192.168.1.2")
  SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=MKE")
  SET(CTEST_TRIGGER_SITE "")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
