%{
#include "netcdf_cmd.h"
extern int yyerror(CMD_Parser * ptr, const char *s);
extern int yylex(CMD_Parser * ptr);
%}
%union {
	char * str;
}
%parse-param { CMD_Parser * ptr }
%lex-param { CMD_Parser * ptr }
%token HELP
%token INFO
%token NUMBER
%token STR
%%

grp: hlp
	| info
	| grp grp
	;

hlp: HELP
	;

info: INFO
	| INFO NUMBER
	| INFO STR
	;
%%

int yyerror(CMD_Parser * ptr, const char * s)
{
	return 0;
}

int yylex(CMD_Parser * ptr)
{
	return ptr->next();
}

